/**
 * Resolves a free-text city (optionally with a country, same "City, Country"
 * shape `parseDestinationQuery` already splits for both `destination` and
 * airport lookups) to real geographic coordinates, against the static
 * dataset generated by `scripts/generate-city-coordinates.ts`
 * (`city-coordinates-data.ts`, do not hand-edit that file). Exists purely to
 * feed `findNearestAirportForCity` (`src/domain/airport-lookup.ts`) — a
 * city's coordinates alone aren't useful anywhere else in this app.
 *
 * Deliberately a ~34,000-city public dataset, not just this app's own
 * ~640-destination seed catalog: an arbitrary user-typed `origin` (a home
 * city, never itself a seeded `destination`) needs the same fallback path,
 * and a broader real dataset gives it real odds of resolving too.
 */
import { CITY_COORDINATES_RAW } from "./city-coordinates-data";

export interface CityCoordinates {
  name: string;
  country: string;
  lat: number;
  lon: number;
}

function normalize(value: string): string {
  return value.trim().toLowerCase();
}

/**
 * GeoNames' own primary `name`/`asciiname` for some real, well-known cities
 * is the native-language form rather than the common English name a
 * traveler (or this app's own seed catalog, `scripts/data/cities.ts`) would
 * type — e.g. "Koeln" for Cologne, "Frankfurt am Main" for bare "Frankfurt".
 * Tried indexing every Latin-script alternate name from GeoNames'
 * `alternatenames` field to close this generally instead of hand-listing
 * cases (`generate-city-coordinates.ts`'s own docstring has the full
 * story); reverted — that file has no per-entry language tag, so even a
 * same-script filter let through enough historical/multi-language noise to
 * balloon the dataset 6x for marginal benefit. This is the narrower,
 * verified alternative: each entry here was found by cross-referencing this
 * app's own ~640-destination seed catalog against GeoNames' real
 * `alternatenames` data for a same-country match (2026-09-22) — not
 * guessed — so this list only grows when a real destination actually needs
 * it, checked against real data each time.
 */
const COMMON_NAME_ALIASES: Record<string, string> = {
  "washington d.c.": "Washington",
  "quebec city": "Quebec",
  bariloche: "San Carlos de Bariloche",
  buzios: "Armacao dos Buzios",
  "st andrews": "Saint Andrews",
  frankfurt: "Frankfurt am Main",
  cologne: "Koeln",
  bruges: "Brugge",
  ghent: "Gent",
  "luxembourg city": "Luxembourg",
  lucerne: "Luzern",
  malmo: "Malmoe",
  "ibiza town": "Ibiza",
  saranda: "Sarande",
  ephesus: "Selcuk",
  "siwa oasis": "Siwah",
  marrakech: "Marrakesh",
  djerba: "Houmt Souk",
  "port elizabeth": "Gqeberha",
  vilanculos: "Vilankulo",
  darjeeling: "Darjiling",
  pondicherry: "Puducherry",
  ulaanbaatar: "Ulan Bator",
  pingyao: "Gutao",
  hualien: "Hualien City",
  "koh samui": "Ko Samui",
  ayutthaya: "Phra Nakhon Si Ayutthaya",
  cebu: "Cebu City",
};

/** Sorted by population descending at generation time (`generate-city-coordinates.ts`) — preserved here so the first entry for an ambiguous bare name (no country given) is its best-known real place, not an arbitrary smaller town that happens to share the name. */
const citiesByName = new Map<string, CityCoordinates[]>();
for (const [name, country, lat, lon] of CITY_COORDINATES_RAW) {
  const key = normalize(name);
  const list = citiesByName.get(key);
  const entry = { name, country, lat, lon };
  if (list) list.push(entry);
  else citiesByName.set(key, [entry]);
}

/**
 * Looks up a free-text city's real coordinates. When `country` is given,
 * only a same-country candidate is ever returned — `null` otherwise, even
 * if a same-named place exists elsewhere. Found necessary live 2026-09-22:
 * an earlier version fell through to the highest-population candidate
 * globally whenever the given country didn't match, which silently
 * resolved "Tuscany" (given as "Tuscany, Italy" — no such populated place
 * in this dataset; Tuscany is a region, not a city) to a same-named
 * Calgary, Canada neighborhood instead — confidently wrong, and a
 * meaningfully worse failure mode for a travel app than an honest "can't
 * resolve." Only with no `country` at all is the highest-population
 * same-name candidate returned, on the theory that a genuinely bare name
 * with no country signal anywhere (rare in practice — see
 * `findNearestAirportForCity`'s own `preferredCountry` parameter, which
 * covers the one real case this app has of a country-less query) is best
 * served by its best-known real place rather than failing outright.
 */
export function findCityCoordinates(city: string, country?: string): CityCoordinates | null {
  const key = normalize(city);
  const candidates = citiesByName.get(key) ?? citiesByName.get(normalize(COMMON_NAME_ALIASES[key] ?? ""));
  if (!candidates || candidates.length === 0) return null;
  if (country) {
    const wantedCountry = normalize(country);
    return candidates.find((c) => normalize(c.country) === wantedCountry) ?? null;
  }
  return candidates[0];
}
